version: '2.2'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: poc-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - poc-net
    expose:
      - "2181"

  kafka:
    image: bitnami/kafka:2.8.0
    container_name: poc-kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: poc-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENERS: POC://:9092,INTERNAL://:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: POC://poc-kafka:9092,INTERNAL://poc-kafka:9091
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: POC:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_NUM_IO_THREADS: 64
      KAFKA_CFG_NUM_NETWORK_THREADS: 128
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_NUM_PARTITIONS: 16
      KAFKA_CFG_OFFSETS_RETENTION_MINUTES: 60
      KAFKA_CFG_LOG_RETENTION_HOURS: 1
      KAFKA_CFG_LOG_RETENTION_BYTES: 1073741824
    networks:
      - poc-net
    expose:
      - "9092"

  poc-back:
    image: org.chusete81/poc-back
    container_name: poc-back
    networks:
      - poc-net
    expose:
      - "9000"

  poc-connectors:
    image: org.chusete81/poc-connectors
    container_name: poc-connectors
    environment:
      POC_CC_KAFKA_URL: poc-kafka:9092
      POC_CC_CONN_BACKEND_URL: http://poc-back:9000/invoke
    networks:
      - poc-net
    expose:
      - "8900"

  poc-hub:
    image: org.chusete81/poc-hub
    container_name: poc-hub
    environment:
      POC_CC_KAFKA_URL: poc-kafka:9092
    networks:
      - poc-net
    expose:
      - "8888"

  poc-web:
    image: org.chusete81/poc-web
    container_name: poc-web
    environment:
      POC_CC_HUB_ENDPOINT: http://poc-hub:8888
    networks:
      - poc-net
    ports:
      - "8080:8080"
      
networks:
  poc-net:
    driver: bridge
